export const mockInvestors = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '+1-555-0123',
    investmentAmount: 250000,
    currentValue: 275000,
    roi: 10,
    joinDate: '2023-01-15',
    profilePicture: '/kuldeep-maurya.jpg',
    type: 'individual', // individual, institutional, angel
    riskProfile: 'moderate', // conservative, moderate, aggressive
    investmentStage: 'seed', // seed, series-a, series-b
    portfolio: [
      { company: 'Pushpak O2', percentage: 100, invested: 250000, current: 275000 },
    ],
    communicationLog: [
      {
        id: 'comm1',
        date: '2024-01-15',
        type: 'email', // email, call, meeting
        subject: 'Q4 2023 Performance Update',
        summary: 'Shared quarterly performance report and upcoming milestones.',
        followUp: null,
      },
    ],
    documents: ['investment-agreement.pdf', 'kyc.pdf', 'tax-forms.pdf'],
    status: 'active', // active, inactive, exited
    lastContact: '2024-01-15',
    nextFollowUp: '2024-04-15',
    notes: 'Long-term investor interested in sustainable aviation. Regular updates requested.',
    tags: ['individual', 'moderate-risk', 'sustainable-investing'],
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '+1-555-0456',
    investmentAmount: 150000,
    currentValue: 165000,
    roi: 10,
    joinDate: '2023-03-20',
    profilePicture: '/next.svg',
    type: 'angel',
    riskProfile: 'aggressive',
    investmentStage: 'seed',
    portfolio: [
      { company: 'Pushpak O2', percentage: 100, invested: 150000, current: 165000 },
    ],
    communicationLog: [
      {
        id: 'comm2',
        date: '2024-01-10',
        type: 'meeting',
        subject: 'Technical Demo and Strategy Discussion',
        summary: 'Presented hydrogen technology demo and discussed expansion plans.',
        followUp: '2024-02-10',
      },
    ],
    documents: ['investment-agreement.pdf', 'kyc.pdf'],
    status: 'active',
    lastContact: '2024-01-10',
    nextFollowUp: '2024-02-10',
    notes: 'Angel investor with aviation background. Interested in technical developments.',
    tags: ['angel', 'aggressive-risk', 'aviation-expert'],
  },
  {
    id: '3',
    name: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    phone: '+1-555-0789',
    investmentAmount: 300000,
    currentValue: 330000,
    roi: 10,
    joinDate: '2023-05-10',
    profilePicture: '/next.svg',
    type: 'institutional',
    riskProfile: 'moderate',
    investmentStage: 'seed',
    portfolio: [
      { company: 'Pushpak O2', percentage: 100, invested: 300000, current: 330000 },
    ],
    communicationLog: [
      {
        id: 'comm3',
        date: '2024-01-08',
        type: 'call',
        subject: 'Portfolio Review and Compliance Update',
        summary: 'Reviewed investment performance and discussed regulatory compliance.',
        followUp: '2024-03-08',
      },
    ],
    documents: ['investment-agreement.pdf', 'kyc.pdf', 'compliance-check.pdf'],
    status: 'active',
    lastContact: '2024-01-08',
    nextFollowUp: '2024-03-08',
    notes: 'Institutional investor. Requires formal reporting and compliance updates.',
    tags: ['institutional', 'moderate-risk', 'compliance-focused'],
  },
  {
    id: '4',
    name: 'Robert Chen',
    email: 'robert.chen@vc-firm.com',
    phone: '+1-555-0321',
    investmentAmount: 500000,
    currentValue: 550000,
    roi: 10,
    joinDate: '2023-07-15',
    profilePicture: '/next.svg',
    type: 'institutional',
    riskProfile: 'aggressive',
    investmentStage: 'series-a',
    portfolio: [
      { company: 'Pushpak O2', percentage: 100, invested: 500000, current: 550000 },
    ],
    communicationLog: [
      {
        id: 'comm4',
        date: '2024-01-12',
        type: 'meeting',
        subject: 'Series A Preparation and Due Diligence',
        summary: 'Discussed Series A funding plans and provided additional due diligence materials.',
        followUp: '2024-02-12',
      },
    ],
    documents: ['term-sheet.pdf', 'due-diligence.pdf', 'investment-agreement.pdf'],
    status: 'active',
    lastContact: '2024-01-12',
    nextFollowUp: '2024-02-12',
    notes: 'VC firm lead. Actively involved in governance and strategic decisions.',
    tags: ['vc-firm', 'aggressive-risk', 'governance'],
  },
  {
    id: '5',
    name: 'Maria Gonzalez',
    email: 'maria.gonzalez@impact-invest.com',
    phone: '+1-555-0654',
    investmentAmount: 200000,
    currentValue: 220000,
    roi: 10,
    joinDate: '2023-09-01',
    profilePicture: '/next.svg',
    type: 'institutional',
    riskProfile: 'moderate',
    investmentStage: 'seed',
    portfolio: [
      { company: 'Pushpak O2', percentage: 100, invested: 200000, current: 220000 },
    ],
    communicationLog: [
      {
        id: 'comm5',
        date: '2024-01-05',
        type: 'email',
        subject: 'Impact Report and ESG Metrics',
        summary: 'Shared environmental impact report and ESG performance metrics.',
        followUp: '2024-04-05',
      },
    ],
    documents: ['impact-agreement.pdf', 'esg-framework.pdf'],
    status: 'active',
    lastContact: '2024-01-05',
    nextFollowUp: '2024-04-05',
    notes: 'Impact investor focused on sustainable aviation. Requires ESG reporting.',
    tags: ['impact-investor', 'moderate-risk', 'esg-focused'],
  },
];