export const mockTechnologies = [
  {
    id: '1',
    title: 'Smart Charging System',
    slug: 'smart-charging-system',
    description: 'Automated battery charging with intelligent power management for rapid turnaround and maximum efficiency.',
    category: 'Infrastructure',
    status: 'active', // active, development, deprecated
    version: '2.1.0',
    releaseDate: '2023-12-15',
    lastUpdated: '2024-01-10',
    featuredImage: '/charging-tray.gif',
    images: ['/charging-tray.gif', '/charging-station.jpg'],
    videos: [],
    specifications: {
      powerOutput: '150kW',
      chargingTime: '15 minutes',
      compatibility: 'H2-Series aircraft',
      automation: 'AI-powered',
    },
    features: [
      'Rapid charging capability',
      'Intelligent power distribution',
      'Remote monitoring',
      'Safety protocols',
      'Weather protection',
    ],
    partners: ['partner1', 'partner2'],
    documentation: ['manual.pdf', 'specs.pdf'],
    downloads: 1250,
    views: 3400,
    isFeatured: true,
  },
  {
    id: '2',
    title: 'Hydrogen Refueling',
    slug: 'hydrogen-refueling',
    description: 'Quick hydrogen fuel cell replenishment enabling extended range and sustainable operations.',
    category: 'Propulsion',
    status: 'active',
    version: '1.8.2',
    releaseDate: '2023-10-20',
    lastUpdated: '2024-01-05',
    featuredImage: '/hydrogen-filling.gif',
    images: ['/hydrogen-filling.gif', '/refueling-station.jpg'],
    videos: ['https://example.com/hydrogen-refueling-demo.mp4'],
    specifications: {
      capacity: '50kg H2',
      fillTime: '5 minutes',
      pressure: '700 bar',
      purity: '99.99%',
    },
    features: [
      'Ultra-fast refueling',
      'High-pressure storage',
      'Safety systems',
      'Quality monitoring',
      'Automated operation',
    ],
    partners: ['partner3'],
    documentation: ['safety-manual.pdf', 'tech-specs.pdf'],
    downloads: 890,
    views: 2100,
    isFeatured: true,
  },
  {
    id: '3',
    title: 'Automated Hangar',
    slug: 'automated-hangar',
    description: 'Precision-engineered hangars for seamless aircraft storage, security, and deployment.',
    category: 'Infrastructure',
    status: 'development',
    version: '0.9.1',
    releaseDate: '2024-02-01',
    lastUpdated: '2024-01-20',
    featuredImage: '/gate-open.gif',
    images: ['/gate-open.gif', '/hangar-interior.jpg'],
    videos: [],
    specifications: {
      capacity: '20 aircraft',
      automation: 'Full AI control',
      security: 'Military-grade',
      climate: 'Controlled environment',
    },
    features: [
      'Automated storage',
      'Climate control',
      'Security systems',
      'Maintenance bays',
      'Quick deployment',
    ],
    partners: ['partner4', 'partner5'],
    documentation: ['design-specs.pdf'],
    downloads: 456,
    views: 1200,
    isFeatured: false,
  },
  {
    id: '4',
    title: 'Vertical Takeoff (eVTOL)',
    slug: 'vertical-takeoff-evtol',
    description: 'Runway-independent vertical takeoff and landing designed for dense urban environments.',
    category: 'Aircraft',
    status: 'active',
    version: '3.2.1',
    releaseDate: '2023-08-15',
    lastUpdated: '2024-01-15',
    featuredImage: '/gate-open.gif',
    images: ['/gate-open.gif', '/evtol-flight.jpg'],
    videos: ['https://example.com/evtol-demo.mp4'],
    specifications: {
      maxPayload: '400kg',
      range: '250km',
      speed: '150km/h',
      endurance: '2.5 hours',
    },
    features: [
      'Vertical takeoff/landing',
      'Urban operation',
      'Quiet propulsion',
      'Autonomous flight',
      'Emergency systems',
    ],
    partners: ['partner1', 'partner6'],
    documentation: ['flight-manual.pdf', 'maintenance-guide.pdf'],
    downloads: 2100,
    views: 5600,
    isFeatured: true,
  },
  {
    id: '5',
    title: 'Autonomous Flight',
    slug: 'autonomous-flight',
    description: 'AI-powered navigation with real-time obstacle detection and intelligent route optimization.',
    category: 'Software',
    status: 'active',
    version: '2.5.0',
    releaseDate: '2023-11-10',
    lastUpdated: '2024-01-18',
    featuredImage: '/drone-flight.gif',
    images: ['/drone-flight.gif', '/autonomous-system.jpg'],
    videos: ['https://example.com/autonomous-flight.mp4'],
    specifications: {
      aiModel: 'GPT-4 based',
      detection: '360° obstacle',
      accuracy: '99.9%',
      responseTime: '<100ms',
    },
    features: [
      'Real-time navigation',
      'Obstacle avoidance',
      'Weather adaptation',
      'Route optimization',
      'Fail-safe systems',
    ],
    partners: ['partner7', 'partner8'],
    documentation: ['api-docs.pdf', 'integration-guide.pdf'],
    downloads: 1800,
    views: 4200,
    isFeatured: true,
  },
  {
    id: '6',
    title: 'Fleet Management',
    slug: 'fleet-management',
    description: 'Centralized real-time monitoring, diagnostics, and predictive maintenance scheduling.',
    category: 'Software',
    status: 'active',
    version: '1.9.3',
    releaseDate: '2023-09-05',
    lastUpdated: '2024-01-12',
    featuredImage: '/aircraft-inspection.png',
    images: ['/aircraft-inspection.png', '/fleet-dashboard.jpg'],
    videos: [],
    specifications: {
      monitoring: '24/7 real-time',
      prediction: 'AI-based',
      integration: 'API-first',
      scalability: 'Enterprise-grade',
    },
    features: [
      'Real-time tracking',
      'Predictive maintenance',
      'Performance analytics',
      'Cost optimization',
      'Compliance monitoring',
    ],
    partners: ['partner9'],
    documentation: ['user-manual.pdf', 'api-reference.pdf'],
    downloads: 1650,
    views: 3800,
    isFeatured: false,
  },
];

export const technologyCategories = ['Aircraft', 'Propulsion', 'Infrastructure', 'Software'];
export const technologyStatuses = ['active', 'development', 'deprecated'];

export const getTechnologiesByCategory = (category) => {
  if (category === 'all') return mockTechnologies;
  return mockTechnologies.filter(tech => tech.category === category);
};

export const getTechnologiesByStatus = (status) => {
  if (status === 'all') return mockTechnologies;
  return mockTechnologies.filter(tech => tech.status === status);
};

export const getTechnologyById = (id) => mockTechnologies.find(tech => tech.id === id);

export const getTechnologyBySlug = (slug) => mockTechnologies.find(tech => tech.slug === slug);

export const getFeaturedTechnologies = () => mockTechnologies.filter(tech => tech.isFeatured);